server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    client_max_body_size 10M;
    root /usr/share/nginx/html;
    index index.html;

    # Servir solo el Frontend de React
    location / {
        try_files $uri $uri/ /index.html;
    }
}